(dp0
ccopy_reg
_reconstructor
p1
(cpraw.objects
Subreddit
p2
c__builtin__
object
p3
Ntp4
Rp5
(dp6
S'_url'
p7
S'http://www.reddit.com/r/forhire/'
p8
sS'_listing_urls'
p9
(lp10
S'http://www.reddit.com/r/forhire/new/.json'
p11
aS'http://www.reddit.com/r/forhire/.json'
p12
aS'http://www.reddit.com/r/forhire/top/.json'
p13
aS'http://www.reddit.com/r/forhire/controversial/.json'
p14
asS'_info_url'
p15
S'http://www.reddit.com/r/forhire/about/'
p16
sS'id'
p17
V2qzbh
p18
sS'display_name'
p19
Vforhire
p20
sS'header_img'
p21
Vhttp://thumbs.reddit.com/t5_2qzbh.png?v=5e4651634ca1aa93138f122fe2d7538f
p22
sS'description_html'
p23
V&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;h3&gt;In Soviet Russia, jobs hunt you! Follow &lt;a href="http://twitter.com/redditforhire"&gt;@redditforhire&lt;/a&gt; on Twitter.&lt;/h3&gt;\u000a\u000a&lt;hr/&gt;\u000a\u000a&lt;p&gt;&lt;strong&gt;search all job reddits&lt;/strong&gt;: &lt;a href="/r/forhire/search?q=title%3A&amp;#x27;%5Bhiring%5D&amp;#x27;+OR+flair%3AHiring+reddit%3Aforhire+OR+reddit%3Ajobbit+OR+reddit%3A:jobopenings&amp;amp;sort=new&amp;amp;t=all"&gt;hiring&lt;/a&gt; / &lt;a href="/r/forhire/search?q=title%3A&amp;#x27;%5Bfor+hire%5D&amp;#x27;+OR+flair%3Afor+hire+reddit%3Aforhire+OR+reddit%3Ajobbit+OR+reddit%3A:jobopenings&amp;amp;sort=new&amp;amp;t=all"&gt;for hire&lt;/a&gt; / &lt;a href="/r/forhire+jobbit+jobopenings/new?sort=new"&gt;all&lt;/a&gt; &lt;/p&gt;\u000a\u000a&lt;p&gt;&lt;strong&gt;lists&lt;/strong&gt;: &lt;a href="/r/forhire/w/local"&gt;local listings&lt;/a&gt; / &lt;a href="/r/forhire/w/field"&gt;field listings&lt;/a&gt;&lt;/p&gt;\u000a\u000a&lt;hr/&gt;\u000a\u000a&lt;blockquote&gt;\u000a&lt;p&gt;&lt;a href="/r/forhire/submit?title=%5BHiring%5D+Title+Goes+Here&amp;amp;text=Put+a+job+description,+location+if+applicable,+and+how+you+want+to+be+contacted+here."&gt;Hire a Redditor&lt;/a&gt;&lt;/p&gt;\u000a&lt;/blockquote&gt;\u000a\u000a&lt;p&gt;&lt;strong&gt;if you&amp;#39;re hiring&lt;/strong&gt;:&lt;/p&gt;\u000a\u000a&lt;ul&gt;\u000a&lt;li&gt;&lt;p&gt;Preface with [hiring] (click green button above)&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;put the basics in the headline.  what&amp;#39;s the job? where is it located? etc.&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;be specific.  include a job description (or a link to one), requirements etc. in the top text.&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;indicate how you would like interested parties to follow up.  pm? email? phone?&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;pay in currency, not in equity. &lt;a href="/comments/1716w0"&gt;more info&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;paid and unpaid internships go &lt;a href="/r/internships"&gt;here&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;try crossposting to a &lt;a href="/r/forhire/w/local"&gt;local forhire subreddit&lt;/a&gt; too&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;[one time projects] consider listing a budget (&lt;a href="/comments/1716w0/budget/c82acno?context=2"&gt;more info&lt;/a&gt;)&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;&lt;strong&gt;&lt;a href="/r/forhire/submit?title=%5BHiring%5D+Title+Goes+Here&amp;amp;text=Put+a+job+description,+location+if+applicable,+and+how+you+want+to+be+contacted+here."&gt;click here&lt;/a&gt;&lt;/strong&gt; to post your Hiring thread&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;[freelance jobs] type prospective employee names into the searchbox above to find reviews&lt;/p&gt;&lt;/li&gt;\u000a&lt;/ul&gt;\u000a\u000a&lt;blockquote&gt;\u000a&lt;p&gt;&lt;a href="/r/forhire/submit?title=%5BFor%20Hire%5D+Title+Goes+Here&amp;amp;text=Put+your+location+and+skills+here,+as+well+as+how+to+contact+you."&gt;Get Hired&lt;/a&gt;&lt;/p&gt;\u000a&lt;/blockquote&gt;\u000a\u000a&lt;p&gt;&lt;strong&gt;if you want to be hired&lt;/strong&gt;:&lt;/p&gt;\u000a\u000a&lt;ul&gt;\u000a&lt;li&gt;&lt;p&gt;preface with [for hire] (click green button above)&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;put the basics in the headline.  what do you do? where can you do it? etc.&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;be specific.  include a portfolio or resume (or a link to one) in the top text.  &lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;do not include any &lt;a href="http://www.eeoc.gov/facts/qanda.html"&gt;EEOC protected statuses&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;indicate how you would like interested parties to follow up.  pm? email? phone?&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;This is a job board, &lt;a href="/r/forhire/comments/18cjkd"&gt;not a billboard&lt;/a&gt;. Please think about if your post is appropriate. &lt;strong&gt;No B2B&lt;/strong&gt;&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;&lt;strong&gt;&lt;a href="/r/forhire/submit?title=%5BFor%20Hire%5D+Title+Goes+Here&amp;amp;text=Put+your+location+and+skills+here,+as+well+as+how+to+contact+you."&gt;click here&lt;/a&gt;&lt;/strong&gt; to post your For Hire thread&lt;/p&gt;&lt;/li&gt;\u000a&lt;/ul&gt;\u000a\u000a&lt;p&gt;&lt;strong&gt;also&lt;/strong&gt;:&lt;/p&gt;\u000a\u000a&lt;ul&gt;\u000a&lt;li&gt;&lt;p&gt;much of the communication with submitters is via pm, so don&amp;#39;t be discouraged if you don&amp;#39;t see a lot of public commenting! &lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;URL shorteners (like bitly) = insta-spammed, so don&amp;#39;t use them&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;click &amp;#39;flair&amp;#39; by your link to update things&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;you look nice in that shirt&lt;/p&gt;&lt;/li&gt;\u000a&lt;li&gt;&lt;p&gt;you might be interested in &lt;a href="/r/jobs"&gt;/r/jobs&lt;/a&gt;, &lt;a href="/r/freelance"&gt;/r/freelance&lt;/a&gt;, &lt;a href="/r/resumes"&gt;/r/resumes&lt;/a&gt; or &lt;a href="/r/internships"&gt;/r/internships&lt;/a&gt;.&lt;/p&gt;&lt;/li&gt;\u000a&lt;/ul&gt;\u000a\u000a&lt;p&gt;&lt;strong&gt;testimonials&lt;/strong&gt;&lt;/p&gt;\u000a\u000a&lt;p&gt;Feel free to post one with [&lt;a href="/r/forhire/search?q=title%3A%27%5Btestimonial%5D%27+&amp;amp;restrict_sr=on&amp;amp;sort=new"&gt;testimonial&lt;/a&gt;].&lt;/p&gt;\u000a\u000a&lt;p&gt;Take a look at our &lt;a href="/r/forhire/comments/1agvw5/rforhire_testimonials/"&gt;ever-growing list of satisfied candidates and managers!&lt;/a&gt;&lt;/p&gt;\u000a\u000a&lt;hr/&gt;\u000a\u000a&lt;p&gt;Suggest more by &lt;a href="/message/compose?to=#forhire"&gt;messaging the mods&lt;/a&gt; (no external links, sorry, check out &lt;a href="http://www.reddit.com/ad_inq/"&gt;sponsored links&lt;/a&gt;)&lt;/p&gt;\u000a&lt;/div&gt;&lt;!-- SC_ON --&gt;
p24
sS'title'
p25
Vredditors for hire
p26
sS'over18'
p27
I00
sS'_underscore_names'
p28
NsS'header_title'
p29
Vredditors for hire
p30
sS'description'
p31
V###In Soviet Russia, jobs hunt you! Follow [@redditforhire](http://twitter.com/redditforhire) on Twitter.\u000a\u000a---\u000a\u000a**search all job reddits**: [hiring](/r/forhire/search?q=title%3A'[hiring]'+OR+flair%3AHiring+reddit%3Aforhire+OR+reddit%3Ajobbit+OR+reddit%3A:jobopenings&amp;sort=new&amp;t=all) / [for hire](/r/forhire/search?q=title%3A'[for+hire]'+OR+flair%3Afor+hire+reddit%3Aforhire+OR+reddit%3Ajobbit+OR+reddit%3A:jobopenings&amp;sort=new&amp;t=all) / [all](/r/forhire+jobbit+jobopenings/new?sort=new) \u000a\u000a**lists**: [local listings](/r/forhire/w/local) / [field listings](/r/forhire/w/field)\u000a\u000a---\u000a&gt;[Hire a Redditor](/r/forhire/submit?title=[Hiring]+Title+Goes+Here&amp;text=Put+a+job+description,+location+if+applicable,+and+how+you+want+to+be+contacted+here.)\u000a\u000a**if you're hiring**:\u000a\u000a- Preface with [hiring] (click green button above)\u000a\u000a- put the basics in the headline.  what's the job? where is it located? etc.\u000a\u000a- be specific.  include a job description (or a link to one), requirements etc. in the top text.\u000a\u000a- indicate how you would like interested parties to follow up.  pm? email? phone?\u000a\u000a- pay in currency, not in equity. [more info](/comments/1716w0)\u000a\u000a- paid and unpaid internships go [here](/r/internships)\u000a\u000a- try crossposting to a [local forhire subreddit](/r/forhire/w/local) too\u000a\u000a- [one time projects] consider 